# Use root/example as user/password credentials
version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    depends_on: 
      - mongodb
    volumes:
      - .:/app